name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]

env:
  GRIDDB_SERVER_NAME: "griddb"
  GRIDDB_NOTIFICATION_ADDRESS: "239.0.0.1"
  GRIDDB_NOTIFICATION_PORT: "31999"
  GRIDDB_USERNAME: "admin"
  GRIDDB_PASSWORD: "admin"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: ${{ secrets.PASSPHRASE }}
      - name: Create and run GridDB server
        run: . .github/workflows/function.sh && run_griddb_server
      - name: Turn off firewall
        run: . .github/workflows/function.sh && firewall_disable
      - name: Build package Java Client
        run: . .github/workflows/function.sh && build_java_client
      - name: Run sample Java Client
        run: . .github/workflows/function.sh && run_sample
      - name: Publish to the Maven Central Repository
        run: cd java_client && mvn clean --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
